### ISSUE TITLE
输出里的 * 是什么意思呢？

### ISSUE THREAD

**Issue by luochen1990** [sjlleo/nexttrace-core#129]
哈喽，这是个非常不错的软件！ 非常感谢， 我之前用的 https://stefansundin.github.io/traceroute-mapper/ 但是发现这个项目好像不怎么维护了，非常高兴看到一个更好的替代品！

但是发现几个小问题，不知道是bug还是feature，不管怎么样我先反馈一下:

1. `-m` 参数似乎没有效果，即使我给了 64， 但还是会出现  `traceroute to 106.37.67.1, 30 hops max, 32 byte packets` 这样的提示。
2. 有时会输出一长串 星号 （`*`），但是不明白是什么意思
3. 不知道这个库是怎么处理代理的，代理会不会影响它的正确工作？
4. `traceroute to 202.101.21.178, 30 hops max, 32 byte packets` 似乎是暗示一次traceroute过程结束了，但是它却是在下一次开始 （下面第二份输出中的 `『上海 电信 163 AS4134 』`） 的后面才打印的，不知道这是 bug 还是 feature ？

复现方式:

```
nexttrace -F -T -m 64 www.google.com
```

相关输出:

```
『杭州 电信 163 AS4134 』traceroute to 61.164.23.196, 30 hops max, 32 byte packets
1   10.40.128.1     *        [RFC1918]        局域网
0.77 ms / 0.83 ms / 0.83 ms
2   115.195.128.1   AS4134   [CHINANET-ZJ]    中国 浙江省 杭州市  chinatelecom.com.cn  电信3.47 ms / 3.69 ms / 3.71 ms
3   *
4   *
5   *
6   *
7   *
8   *
9   *
10  *
11  *
12  *
13  *
14  *
```

下面是另一段输出:
```
『北京 电信 163 AS4134 』traceroute to 106.37.67.1, 30 hops max, 32 byte packets
1   10.40.128.1     *        [RFC1918]        局域网
0.70 ms / 0.80 ms / 1.20 ms
2   115.195.128.1   AS4134   [CHINANET-ZJ]    中国 浙江省 杭州市  chinatelecom.com.cn  电信3.16 ms / 3.35 ms / 3.60 ms
3   *
4   *
5   *
6   202.97.98.133   AS4134   [CHINANET-BB]    中国 北京市   chinatelecom.com.cn  电信29.45 ms / * ms / * ms
7   *
8   106.37.67.1     AS4847   [CHINANET-HN]    中国 北京市   chinatelecom.cn
1.67.37.106.static.bjtelecom.net          30.31 ms / * ms / * ms

『上海 电信 163 AS4134 』traceroute to 202.101.21.178, 30 hops max, 32 byte packets
1   10.40.128.1     *        [RFC1918]        局域网
0.67 ms / 0.84 ms / 0.82 ms
2   115.195.128.1   AS4134   [CHINANET-ZJ]    中国 浙江省 杭州市  chinatelecom.com.cn  电信3.63 ms / 3.85 ms / 4.04 ms
```

**Comment by tsosunchia** [comment]
你好👋，

> `nexttrace -F -T -m 64 www.google.com`

此用法是错误的，
- `-F` <==> fast_trace mode
- `-T` <==> tcp mode
- `-m 64` <==> max_hops=64

同时你还加了`www.google.com`，在这种情况下NEXTTRACE会将您的输入理解为`-F -T -m 64`，即使用TCP进行快速路由测试且max_hops为64.(而不是对www.google.com进行此测试)

建议您再仔细看一下`--help`或者本项目的README。

>1. `-m` 参数似乎没有效果，即使我给了 64， 但还是会出现  `traceroute to 106.37.67.1, 30 hops max, 32 byte packets` 这样的提示。

此问题已在`v1.1.6`中修复，请更新您的NEXTTRACE。

>2. 有时会输出一长串 星号 （`*`），但是不明白是什么意思

在路由追踪测试中，并不是所有设备都响应的，对于不响应的会显示为*

>3. 不知道这个库是怎么处理代理的，代理会不会影响它的正确工作？

NEXTTRACE支持3种追踪 ICMP、TCP、UDP，会不会影响其工作要看您的代理设置了，具体问题具体分析这里无法解答。

>4. `traceroute to 202.101.21.178, 30 hops max, 32 byte packets` 似乎是暗示一次traceroute过程结束了，但是它却是在下一次开始 （下面第二份输出中的 `『上海 电信 163 AS4134 』`） 的后面才打印的，不知道这是 bug 还是 feature ？

您这里使用的是fast_trace mode，会自动测试一组IP，这里是正常现象。

**Comment by sjlleo** [comment]
之前 tso 同学已经解答了您的疑问，但是我必须补充一点，此类软件成熟以后通常就不会再频繁维护。

您之前提到的 traceroute-mapper 是一个非常不错的 mtr 结果解析工具，这个项目在 NextTrace 发行之前就已经存在。

此类软件所谓的“维护”其实就是在加一些可选功能，会使得软件更加臃肿，现在的状态已经是它的最佳状态，等 NextTrace 功能都彻底成熟以后，未来也会逐渐变成 traceroute-mapper 一样。

谢谢

**Comment by luochen1990** [comment]
@tsosunchia 
1. 可能我没有正确理解 -F 参数的含义， 我以为加上它只是用不同但更快速的策略做同样的事情。
2. 明白了，谢谢。 不过也许可以像 局域网 一样，在 * 号后面附加一个类似的说明。

**Comment by luochen1990** [comment]
@sjlleo  谢谢告知。不过既然您认为  traceroute-mapper  已经非常好了， 那么 nexttrace 和它的差异主要在哪些点呢？

**Comment by tsosunchia** [comment]
> 那么 nexttrace 和它的差异主要在哪些点呢？

NEXTTRACE的大部分使用场景并不是在网页上查看，相反的，traceroute-mapper专注于网页的可视化显示

>在 * 号后面附加一个类似的说明

该显示在同类软件中是有惯例的，为了保持简洁以及通用，我们在未来不打算改变此处。

**Comment by luochen1990** [comment]
OK, 了解， 谢谢回复 :)
