### ISSUE TITLE
北京移动-LeoMoeAPI 追踪一个目的ip后只有目的ip的信息

### ISSUE THREAD

**Issue by ttytu2** [sjlleo/nexttrace-core#130]
动态公网ip
网段:120.244.127.x

**Comment by tsosunchia** [comment]
## 你正在使用哪个版本的 nexttrace？




## 你看到的异常现象是什么？




## 你期待看到的正常表现是怎样的？



## 请附上你的命令




## 请附上出错时软件输出的错误信息

## 是否查询过本仓库wiki有没有类似错误




请按模版填写完整信息后，重新提交issue
