### ISSUE TITLE
当到目标地址的hop只有一个时，tracer 的PrintFunc会进入无限循环状态

### ISSUE THREAD

**Issue by wujiu595** [sjlleo/nexttrace-core#133]
## 你正在使用哪个版本的 nexttrace？
v1.1.7-1

## 你看到的异常现象是什么？
当到目标地址的hop为1时，tracer 的PrintFunc会进入无限循环状态

## 你期待看到的正常表现是怎样的？
可以正常trace

**Comment by wujiu595** [comment]
可以trace 本地ip或者局域网ip进行测试

**Comment by tsosunchia** [comment]
> 可以trace 本地ip或者局域网ip进行测试

此功能完全可以使用更轻量的PING来实现，NEXTTRACE无意做类似任务。
