### ISSUE TITLE
icmp tracer 的PrintFunc() 方法会在 trace本机ip或者局域网ip时进入无限循环的状态

### ISSUE THREAD

**Issue by wujiu595** [sjlleo/nexttrace-core#134]

**Comment by wujiu595** [comment]
全部的，有且只有一个hop的目标地址都会有这个问题啊

**Comment by tsosunchia** [comment]
请使用PING来执行，此类操作不属于NEXTTRACE设计用途。

**Comment by sjlleo** [comment]
只有一个 Hop 的通常会被我们视作想要滥用我们的 API 通过 IP 遍历以爬取我们库 IP 的地理位置信息。

您可以修改代码 Fix 这个问题，但是您最好不要使用 LeoMoeAPI，因为我们的风控系统随时可能会封禁您的 client 的 LeoMoeAPI Access 权限，后果由您自行承担。

**Comment by wujiu595** [comment]
好的 明白了
