### ISSUE TITLE
win11上无法使用

### ISSUE THREAD

**Issue by toyo2333** [sjlleo/nexttrace-core#135]
最新版，windows11上运行。小白 不知道怎么弄

2023/06/09 13:58:19 dial: websocket: bad handshake
Domain -? Lookup Fail.

另外有一个问题，如果我在windows客户端上使用代理。然后命令行运行工具，访问目标地址选Google.com

那么输出结果会包含我的VPS节点么？

**Comment by tsosunchia** [comment]
请看完WIKi再来发ISSUE

**Comment by toyo2333** [comment]
挺烂的，至少besttrace和worsttrace我同样的操作，都能用。88. 垃圾开发者 。

**Comment by tsosunchia** [comment]
> 挺烂的，至少besttrace和worsttrace我同样的操作，都能用。88. 垃圾产品。

爱用不用 轮不到你来狗吠 一分钱不出来当大爷？

**Comment by toyo2333** [comment]
> > 挺烂的，至少besttrace和worsttrace我同样的操作，都能用。88. 垃圾产品。
> 
> 爱用不用 轮不到你来狗吠 一分钱不出来当大爷？

爱开发不开发，做成一坨屎你也配叫？狗屎一样东西还不如我们楼下的编程班的作业，也配出来要饭？渣渣

**Comment by toyo2333** [comment]
> > 挺烂的，至少besttrace和worsttrace我同样的操作，都能用。88. 垃圾产品。
> 
> 爱用不用 轮不到你来狗吠 一分钱不出来当大爷？

这项目本来也不是你原创的从0到1的，装什么B？吃别人剩饭也配叫？搞笑

**Comment by Archeb** [comment]
就应该像隔壁 https://github.com/MetaCubeX/Clash.Meta/issues/611 一样挂起来。
