### ISSUE TITLE
Windows版本无法使用，打开闪退

### ISSUE THREAD

**Issue by idsasad** [sjlleo/nexttrace-core#136]
## 你正在使用哪个版本的 nexttrace？

nexttrace_windows_arm64 最新版本

## 你看到的异常现象是什么？

软件打开就闪退

## 你期待看到的正常表现是怎样的？
正常使用，我运行库都装了，但还是不行

## 请附上你的命令

双击运行后出现一个黑框框，出来后突然关闭

## 请附上出错时软件输出的错误信息
无报错信息，windwos10最新版本

**Comment by isyekong** [comment]
使用终端/CMD运行，与Linux使用方式一致
