### ISSUE TITLE
关于版本号和发布 release 的问题

### ISSUE THREAD

**Issue by ouuan** [sjlleo/nexttrace-core#137]
1. 希望能避免使用 1.1.7-1 这样的版本号，1.1.8 或者 1.1.7.1 都行。（在 Arch 上 1.1.7-1 的版本号是不合法的。）
2. 希望能不要在发布 release 后再进行修改，而是在首次发布时就选择正确的 release/pre-release 选项之类的，否则会有信息错误的窗口期，并且只有首次发布时会发通知邮件，后续修改是没有邮件通知的。可以通过先编写 release draft 后发布的方式来避免修改。

**Comment by tsosunchia** [comment]
> 希望能避免使用 1.1.7-1 这样的版本号，1.1.8 或者 1.1.7.1 都行。（在 Arch 上 1.1.7-1 的版本号是不合法的。）

感谢您的建议，今后我们会注意到这一点的，即使用符合大多数系统规范的版本号命名，但是v1.1.7-1已经发版，很遗憾我们不能撤销了。

> 希望能不要在发布 release 后再进行修改，而是在首次发布时就选择正确的 release/pre-release 选项之类的，否则会有信息错误的窗口期，并且只有首次发布时会发通知邮件，后续修改是没有邮件通知的。可以通过先编写 release draft 后发布的方式来避免修改。

由于要编译的版本太多了，我们只能使用GITHUB ACTIONS来自动发版，考虑到您说的情况，我们今后会尽力减少修改已有release的状态。

**Comment by ouuan** [comment]
> 由于要编译的版本太多了，我们只能使用GITHUB ACTIONS来自动发版，考虑到您说的情况，我们今后会尽力减少修改已有release的状态。

https://github.com/sjlleo/nexttrace-core/blob/34fc2dbf7c6e9c33db6abf0f24349e787775d0ff/.github/workflows/build.yml#L35
